version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:  > 
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=kalman
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - database_proxy

  db:
    image: postgres:13.0
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kalman
      - POSTGRES_PORT=5432
      - TIME_ZONE=UTC
      - USE_TZ=True

    ports:
      - "5434:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    networks:
      - database_proxy

networks:
  database_proxy:
    driver: bridge

